version: '3.8'
services:
  stats-server:
    build: stats_server
    image: stats
    container_name: ewm-stats
    depends_on:
      - main-service
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db

  stats-db:
    image: postgres:14-alpine
    container_name: ewm-stats-db
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  main-service:
    build: main_server
    image: main
    container_name: ewm-main
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main-db

  main-db:
    image: postgres:14-alpine
    container_name: ewm-main-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root