version: '3.1'
services:
  main-server:
    build: main-server
    image: main
    container_name: ewm-main
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/main-db

  main-db:
    image: postgres:14-alpine
    container_name: main-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-server:
    build: stats-server
    image: stats
    container_name: ewm-stats
    ports:
      - "9090:9090"
    depends_on:
      - main-server
      - stats-db
    environment:
      - EWM_SERVER_URL=http://main-server:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stats-db

  stats-db:
    image: postgres:13.7-alpine
    container_name: stats-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root